<?php

/** @var $block \Magento\Framework\View\Element\Template */
/** @var $viewModelProductLabelList \Polish\ProductLabel\ViewModel\ProductLabelList */

$viewModelProductLabelList = $block->getViewModelProductLabelList();
$escaper = $viewModelProductLabelList->getEscaper();
?>
<div class="product-label-container">
    <div class="product-label-image-container">
    <?php foreach ($viewModelProductLabelList->getProductLabels() as $productLabel) : ?>
        <img
            class="product-label-image"
            src="<?= $escaper->escapeUrl($viewModelProductLabelList->getProductLabelImageUrl($productLabel)); ?>"
            alt="<?= $escaper->escapeHtmlAttr(__($productLabel->getTitle())) ?>"
            title="<?= $escaper->escapeHtmlAttr(__($productLabel->getTitle())) ?>"
        />
    <?php endforeach; ?>
    </div>
</div>
